TWITTER_CONSUMER_KEY = '9Yj1qSpyzySSpDI5ty1dA'
TWITTER_CONSUMER_SECRET = '46XJ47V8ZhhladFLefR5KVWf5sPfpxzZC8kuSpsY'
TWITTER_OAUTH_TOKEN = '1133957107-yKNxj8xHXr9kE4vTwKWh9Qzexk7I3GXjty4VBQ8'
TWITTER_OAUTH_SECRET = 'UPR8I3tl1CpeVUChE0kV3F05f6do8j87FgW53xMU'

Twitter.configure do |config|
  config.consumer_key = TWITTER_CONSUMER_KEY
  config.consumer_secret = TWITTER_CONSUMER_SECRET
  config.oauth_token = TWITTER_OAUTH_TOKEN
  config.oauth_token_secret = TWITTER_OAUTH_SECRET
end

