#
# This file contains the configuration of the application
#
:twitter:
  :consumer_key: SF8RlPZT7bUW5QI173sJdg
  :consumer_secret: JopN0OyZ7QQVpkO1DUEkQ5g8q5RlF17kHfEsU9NKo
  
:bitly:
  :username: nicolasrotta
  :key: R_22cf5e4a0887bc301d513339514c0f95