class CreateWeekMaps < ActiveRecord::Migration
  def change
    create_table :week_maps do |t|
      t.references :influencer

      t.integer :mon_0, null: false, default: 0
      t.integer :mon_1, null: false, default: 0
      t.integer :mon_2, null: false, default: 0
      t.integer :mon_3, null: false, default: 0
      t.integer :mon_4, null: false, default: 0
      t.integer :mon_5, null: false, default: 0
      t.integer :mon_6, null: false, default: 0
      t.integer :mon_7, null: false, default: 0
      t.integer :mon_8, null: false, default: 0
      t.integer :mon_9, null: false, default: 0
      t.integer :mon_10, null: false, default: 0
      t.integer :mon_11, null: false, default: 0
      t.integer :mon_12, null: false, default: 0
      t.integer :mon_13, null: false, default: 0
      t.integer :mon_14, null: false, default: 0
      t.integer :mon_15, null: false, default: 0
      t.integer :mon_16, null: false, default: 0
      t.integer :mon_17, null: false, default: 0
      t.integer :mon_18, null: false, default: 0
      t.integer :mon_19, null: false, default: 0
      t.integer :mon_20, null: false, default: 0
      t.integer :mon_21, null: false, default: 0
      t.integer :mon_22, null: false, default: 0
      t.integer :mon_23, null: false, default: 0

      t.integer :tue_0, null: false, default: 0
      t.integer :tue_1, null: false, default: 0
      t.integer :tue_2, null: false, default: 0
      t.integer :tue_3, null: false, default: 0
      t.integer :tue_4, null: false, default: 0
      t.integer :tue_5, null: false, default: 0
      t.integer :tue_6, null: false, default: 0
      t.integer :tue_7, null: false, default: 0
      t.integer :tue_8, null: false, default: 0
      t.integer :tue_9, null: false, default: 0
      t.integer :tue_10, null: false, default: 0
      t.integer :tue_11, null: false, default: 0
      t.integer :tue_12, null: false, default: 0
      t.integer :tue_13, null: false, default: 0
      t.integer :tue_14, null: false, default: 0
      t.integer :tue_15, null: false, default: 0
      t.integer :tue_16, null: false, default: 0
      t.integer :tue_17, null: false, default: 0
      t.integer :tue_18, null: false, default: 0
      t.integer :tue_19, null: false, default: 0
      t.integer :tue_20, null: false, default: 0
      t.integer :tue_21, null: false, default: 0
      t.integer :tue_22, null: false, default: 0
      t.integer :tue_23, null: false, default: 0

      t.integer :wed_0, null: false, default: 0
      t.integer :wed_1, null: false, default: 0
      t.integer :wed_2, null: false, default: 0
      t.integer :wed_3, null: false, default: 0
      t.integer :wed_4, null: false, default: 0
      t.integer :wed_5, null: false, default: 0
      t.integer :wed_6, null: false, default: 0
      t.integer :wed_7, null: false, default: 0
      t.integer :wed_8, null: false, default: 0
      t.integer :wed_9, null: false, default: 0
      t.integer :wed_10, null: false, default: 0
      t.integer :wed_11, null: false, default: 0
      t.integer :wed_12, null: false, default: 0
      t.integer :wed_13, null: false, default: 0
      t.integer :wed_14, null: false, default: 0
      t.integer :wed_15, null: false, default: 0
      t.integer :wed_16, null: false, default: 0
      t.integer :wed_17, null: false, default: 0
      t.integer :wed_18, null: false, default: 0
      t.integer :wed_19, null: false, default: 0
      t.integer :wed_20, null: false, default: 0
      t.integer :wed_21, null: false, default: 0
      t.integer :wed_22, null: false, default: 0
      t.integer :wed_23, null: false, default: 0

      t.integer :thu_0, null: false, default: 0
      t.integer :thu_1, null: false, default: 0
      t.integer :thu_2, null: false, default: 0
      t.integer :thu_3, null: false, default: 0
      t.integer :thu_4, null: false, default: 0
      t.integer :thu_5, null: false, default: 0
      t.integer :thu_6, null: false, default: 0
      t.integer :thu_7, null: false, default: 0
      t.integer :thu_8, null: false, default: 0
      t.integer :thu_9, null: false, default: 0
      t.integer :thu_10, null: false, default: 0
      t.integer :thu_11, null: false, default: 0
      t.integer :thu_12, null: false, default: 0
      t.integer :thu_13, null: false, default: 0
      t.integer :thu_14, null: false, default: 0
      t.integer :thu_15, null: false, default: 0
      t.integer :thu_16, null: false, default: 0
      t.integer :thu_17, null: false, default: 0
      t.integer :thu_18, null: false, default: 0
      t.integer :thu_19, null: false, default: 0
      t.integer :thu_20, null: false, default: 0
      t.integer :thu_21, null: false, default: 0
      t.integer :thu_22, null: false, default: 0
      t.integer :thu_23, null: false, default: 0

      t.integer :fri_0, null: false, default: 0
      t.integer :fri_1, null: false, default: 0
      t.integer :fri_2, null: false, default: 0
      t.integer :fri_3, null: false, default: 0
      t.integer :fri_4, null: false, default: 0
      t.integer :fri_5, null: false, default: 0
      t.integer :fri_6, null: false, default: 0
      t.integer :fri_7, null: false, default: 0
      t.integer :fri_8, null: false, default: 0
      t.integer :fri_9, null: false, default: 0
      t.integer :fri_10, null: false, default: 0
      t.integer :fri_11, null: false, default: 0
      t.integer :fri_12, null: false, default: 0
      t.integer :fri_13, null: false, default: 0
      t.integer :fri_14, null: false, default: 0
      t.integer :fri_15, null: false, default: 0
      t.integer :fri_16, null: false, default: 0
      t.integer :fri_17, null: false, default: 0
      t.integer :fri_18, null: false, default: 0
      t.integer :fri_19, null: false, default: 0
      t.integer :fri_20, null: false, default: 0
      t.integer :fri_21, null: false, default: 0
      t.integer :fri_22, null: false, default: 0
      t.integer :fri_23, null: false, default: 0

      t.integer :sat_0, null: false, default: 0
      t.integer :sat_1, null: false, default: 0
      t.integer :sat_2, null: false, default: 0
      t.integer :sat_3, null: false, default: 0
      t.integer :sat_4, null: false, default: 0
      t.integer :sat_5, null: false, default: 0
      t.integer :sat_6, null: false, default: 0
      t.integer :sat_7, null: false, default: 0
      t.integer :sat_8, null: false, default: 0
      t.integer :sat_9, null: false, default: 0
      t.integer :sat_10, null: false, default: 0
      t.integer :sat_11, null: false, default: 0
      t.integer :sat_12, null: false, default: 0
      t.integer :sat_13, null: false, default: 0
      t.integer :sat_14, null: false, default: 0
      t.integer :sat_15, null: false, default: 0
      t.integer :sat_16, null: false, default: 0
      t.integer :sat_17, null: false, default: 0
      t.integer :sat_18, null: false, default: 0
      t.integer :sat_19, null: false, default: 0
      t.integer :sat_20, null: false, default: 0
      t.integer :sat_21, null: false, default: 0
      t.integer :sat_22, null: false, default: 0
      t.integer :sat_23, null: false, default: 0

      t.integer :sun_0, null: false, default: 0
      t.integer :sun_1, null: false, default: 0
      t.integer :sun_2, null: false, default: 0
      t.integer :sun_3, null: false, default: 0
      t.integer :sun_4, null: false, default: 0
      t.integer :sun_5, null: false, default: 0
      t.integer :sun_6, null: false, default: 0
      t.integer :sun_7, null: false, default: 0
      t.integer :sun_8, null: false, default: 0
      t.integer :sun_9, null: false, default: 0
      t.integer :sun_10, null: false, default: 0
      t.integer :sun_11, null: false, default: 0
      t.integer :sun_12, null: false, default: 0
      t.integer :sun_13, null: false, default: 0
      t.integer :sun_14, null: false, default: 0
      t.integer :sun_15, null: false, default: 0
      t.integer :sun_16, null: false, default: 0
      t.integer :sun_17, null: false, default: 0
      t.integer :sun_18, null: false, default: 0
      t.integer :sun_19, null: false, default: 0
      t.integer :sun_20, null: false, default: 0
      t.integer :sun_21, null: false, default: 0
      t.integer :sun_22, null: false, default: 0
      t.integer :sun_23, null: false, default: 0

      t.timestamps
    end
  end
end
