class AddMoreLocationsToAudience < ActiveRecord::Migration
  def change
    #col
    add_column :audiences, :state_col_amazonas, :int, default: 0, null: false
    add_column :audiences, :state_col_antioquia, :int, default: 0, null: false
    add_column :audiences, :state_col_arauca, :int, default: 0, null: false
    add_column :audiences, :state_col_atlantico, :int, default: 0, null: false
    add_column :audiences, :state_col_bolivar, :int, default: 0, null: false
    add_column :audiences, :state_col_boyaca, :int, default: 0, null: false
    add_column :audiences, :state_col_caldas, :int, default: 0, null: false
    add_column :audiences, :state_col_caqueta, :int, default: 0, null: false
    add_column :audiences, :state_col_casanare, :int, default: 0, null: false
    add_column :audiences, :state_col_cauca, :int, default: 0, null: false
    add_column :audiences, :state_col_cesar, :int, default: 0, null: false
    add_column :audiences, :state_col_choco, :int, default: 0, null: false
    add_column :audiences, :state_col_cordoba, :int, default: 0, null: false
    add_column :audiences, :state_col_cundinamarca, :int, default: 0, null: false
    add_column :audiences, :state_col_guainia, :int, default: 0, null: false
    add_column :audiences, :state_col_guaviare, :int, default: 0, null: false
    add_column :audiences, :state_col_huila, :int, default: 0, null: false
    add_column :audiences, :state_col_la_guajira, :int, default: 0, null: false
    add_column :audiences, :state_col_magdalena, :int, default: 0, null: false
    add_column :audiences, :state_col_meta, :int, default: 0, null: false
    add_column :audiences, :state_col_narino, :int, default: 0, null: false
    add_column :audiences, :state_col_norte_de_santander, :int, default: 0, null: false
    add_column :audiences, :state_col_putumayo, :int, default: 0, null: false
    add_column :audiences, :state_col_quindio, :int, default: 0, null: false
    add_column :audiences, :state_col_risaralda, :int, default: 0, null: false
    add_column :audiences, :state_col_san_andres, :int, default: 0, null: false
    add_column :audiences, :state_col_santander, :int, default: 0, null: false
    add_column :audiences, :state_col_sucre, :int, default: 0, null: false
    add_column :audiences, :state_col_tolima, :int, default: 0, null: false
    add_column :audiences, :state_col_valle_del_cauca, :int, default: 0, null: false
    add_column :audiences, :state_col_vaupes, :int, default: 0, null: false
    add_column :audiences, :state_col_vichada, :int, default: 0, null: false
    add_column :audiences, :state_col_colombia, :int, default: 0, null: false
    #chi
    add_column :audiences, :state_chi_arica, :int, default: 0, null: false
    add_column :audiences, :state_chi_tarapaca, :int, default: 0, null: false
    add_column :audiences, :state_chi_antofogasta, :int, default: 0, null: false
    add_column :audiences, :state_chi_atacama, :int, default: 0, null: false
    add_column :audiences, :state_chi_coquimbo, :int, default: 0, null: false
    add_column :audiences, :state_chi_valparaiso, :int, default: 0, null: false
    add_column :audiences, :state_chi_santiago, :int, default: 0, null: false
    add_column :audiences, :state_chi_ohiggins, :int, default: 0, null: false
    add_column :audiences, :state_chi_maule, :int, default: 0, null: false
    add_column :audiences, :state_chi_biobio, :int, default: 0, null: false
    add_column :audiences, :state_chi_la_araucania, :int, default: 0, null: false
    add_column :audiences, :state_chi_los_rios, :int, default: 0, null: false
    add_column :audiences, :state_chi_los_lagos, :int, default: 0, null: false
    add_column :audiences, :state_chi_aysen, :int, default: 0, null: false
    add_column :audiences, :state_chi_magallanes, :int, default: 0, null: false
    #ecu
    add_column :audiences, :state_ecu_azuay, :int, default: 0, null: false
    add_column :audiences, :state_ecu_bolivar, :int, default: 0, null: false
    add_column :audiences, :state_ecu_canar, :int, default: 0, null: false
    add_column :audiences, :state_ecu_carchi, :int, default: 0, null: false
    add_column :audiences, :state_ecu_chimborazo, :int, default: 0, null: false
    add_column :audiences, :state_ecu_cotopaxi, :int, default: 0, null: false
    add_column :audiences, :state_ecu_el_oro, :int, default: 0, null: false
    add_column :audiences, :state_ecu_esmeraldas, :int, default: 0, null: false
    add_column :audiences, :state_ecu_galapagos, :int, default: 0, null: false
    add_column :audiences, :state_ecu_guayas, :int, default: 0, null: false
    add_column :audiences, :state_ecu_imbabura, :int, default: 0, null: false
    add_column :audiences, :state_ecu_loja, :int, default: 0, null: false
    add_column :audiences, :state_ecu_los_rios, :int, default: 0, null: false
    add_column :audiences, :state_ecu_manabi, :int, default: 0, null: false
    add_column :audiences, :state_ecu_morona_santiago, :int, default: 0, null: false
    add_column :audiences, :state_ecu_napo, :int, default: 0, null: false
    add_column :audiences, :state_ecu_orellana, :int, default: 0, null: false
    add_column :audiences, :state_ecu_pastaza, :int, default: 0, null: false
    add_column :audiences, :state_ecu_pichincha, :int, default: 0, null: false
    add_column :audiences, :state_ecu_santa_elena, :int, default: 0, null: false
    add_column :audiences, :state_ecu_santo_domingo, :int, default: 0, null: false
    add_column :audiences, :state_ecu_sucumbios, :int, default: 0, null: false
    add_column :audiences, :state_ecu_tungurahua, :int, default: 0, null: false
    add_column :audiences, :state_ecu_zamora, :int, default: 0, null: false
    #mex
    add_column :audiences, :state_mex_aguascalientes, :int, default: 0, null: false
    add_column :audiences, :state_mex_baja_california, :int, default: 0, null: false
    add_column :audiences, :state_mex_baja_california_sur, :int, default: 0, null: false
    add_column :audiences, :state_mex_campeche, :int, default: 0, null: false
    add_column :audiences, :state_mex_chiapas, :int, default: 0, null: false
    add_column :audiences, :state_mex_chihuahua, :int, default: 0, null: false
    add_column :audiences, :state_mex_coahuila, :int, default: 0, null: false
    add_column :audiences, :state_mex_colima, :int, default: 0, null: false
    add_column :audiences, :state_mex_distrito_federal, :int, default: 0, null: false
    add_column :audiences, :state_mex_durango, :int, default: 0, null: false
    add_column :audiences, :state_mex_guanajuato, :int, default: 0, null: false
    add_column :audiences, :state_mex_guerrero, :int, default: 0, null: false
    add_column :audiences, :state_mex_hidalgo, :int, default: 0, null: false
    add_column :audiences, :state_mex_jalisco, :int, default: 0, null: false
    add_column :audiences, :state_mex_mexico, :int, default: 0, null: false
    add_column :audiences, :state_mex_michoacan, :int, default: 0, null: false
    add_column :audiences, :state_mex_morelos, :int, default: 0, null: false
    add_column :audiences, :state_mex_nayarit, :int, default: 0, null: false
    add_column :audiences, :state_mex_nuevo_leon, :int, default: 0, null: false
    add_column :audiences, :state_mex_oaxaca, :int, default: 0, null: false
    add_column :audiences, :state_mex_puebla, :int, default: 0, null: false
    add_column :audiences, :state_mex_queretaro, :int, default: 0, null: false
    add_column :audiences, :state_mex_quintana_roo, :int, default: 0, null: false
    add_column :audiences, :state_mex_san_luis, :int, default: 0, null: false
    add_column :audiences, :state_mex_sinaloa, :int, default: 0, null: false
    add_column :audiences, :state_mex_sonora, :int, default: 0, null: false
    add_column :audiences, :state_mex_tabasco, :int, default: 0, null: false
    add_column :audiences, :state_mex_tamaulipas, :int, default: 0, null: false
    add_column :audiences, :state_mex_tlaxcala, :int, default: 0, null: false
    add_column :audiences, :state_mex_veracruz, :int, default: 0, null: false
    add_column :audiences, :state_mex_yucatan, :int, default: 0, null: false
    add_column :audiences, :state_mex_zacatecas, :int, default: 0, null: false
    #par
    add_column :audiences, :state_par_asuncion, :int, default: 0, null: false
    add_column :audiences, :state_par_concepcion, :int, default: 0, null: false
    add_column :audiences, :state_par_san_pedro, :int, default: 0, null: false
    add_column :audiences, :state_par_cordillera, :int, default: 0, null: false
    add_column :audiences, :state_par_guaira, :int, default: 0, null: false
    add_column :audiences, :state_par_caaguazu, :int, default: 0, null: false
    add_column :audiences, :state_par_caazapa, :int, default: 0, null: false
    add_column :audiences, :state_par_itapua, :int, default: 0, null: false
    add_column :audiences, :state_par_misiones, :int, default: 0, null: false
    add_column :audiences, :state_par_paraguari, :int, default: 0, null: false
    add_column :audiences, :state_par_alto_parana, :int, default: 0, null: false
    add_column :audiences, :state_par_central, :int, default: 0, null: false
    add_column :audiences, :state_par_neenbucu, :int, default: 0, null: false
    add_column :audiences, :state_par_amambay, :int, default: 0, null: false
    add_column :audiences, :state_par_canindeyu, :int, default: 0, null: false
    add_column :audiences, :state_par_presidente_hayes, :int, default: 0, null: false
    add_column :audiences, :state_par_alto_paraguay, :int, default: 0, null: false
    add_column :audiences, :state_par_boqueron, :int, default: 0, null: false
    #uru
    add_column :audiences, :state_uru_artigas, :int, default: 0, null: false
    add_column :audiences, :state_uru_canelones, :int, default: 0, null: false
    add_column :audiences, :state_uru_cerro_largo, :int, default: 0, null: false
    add_column :audiences, :state_uru_colonia, :int, default: 0, null: false
    add_column :audiences, :state_uru_durazno, :int, default: 0, null: false
    add_column :audiences, :state_uru_flores, :int, default: 0, null: false
    add_column :audiences, :state_uru_florida, :int, default: 0, null: false
    add_column :audiences, :state_uru_lavalleja, :int, default: 0, null: false
    add_column :audiences, :state_uru_maldonado, :int, default: 0, null: false
    add_column :audiences, :state_uru_montevideo, :int, default: 0, null: false
    add_column :audiences, :state_uru_paysandu, :int, default: 0, null: false
    add_column :audiences, :state_uru_rio_negro, :int, default: 0, null: false
    add_column :audiences, :state_uru_rivera, :int, default: 0, null: false
    add_column :audiences, :state_uru_rocha, :int, default: 0, null: false
    add_column :audiences, :state_uru_salto, :int, default: 0, null: false
    add_column :audiences, :state_uru_san_jose, :int, default: 0, null: false
    add_column :audiences, :state_uru_soriano, :int, default: 0, null: false
    add_column :audiences, :state_uru_tacuarembo, :int, default: 0, null: false
    add_column :audiences, :state_uru_treinta_y_tres, :int, default: 0, null: false
  end
end


