app_country: AR

mercadopago_client_id: 1497418973712885
mercadopago_client_secret: x6s0ZCkYTxMPpbm9gwR0e7irPUsROAgp
mercadopago_currency_id: ARS
mercadopago_paybutton_class: blue-ar-m-sq-arall
mercadopago_acc_id: 534896343
mercadopago_enc: bxcH14rdC9Puu1%2BZULSDEB3x4JA%3D
mercadopago_sonda: 0%2BQzLxNiuh7SAAN06uG3HkzhGiY%3D