app_country: CO

mercadopago_client_id: 3509083693722168
mercadopago_client_secret: agXF3v6ezCuhGaWQNlrS6kpncrc88QWX
mercadopago_currency_id: ARS
mercadopago_paybutton_class: blue-ar-m-sq-arall
mercadopago_acc_id: 534896343
mercadopago_enc: bxcH14rdC9Puu1%2BZULSDEB3x4JA%3D
mercadopago_sonda: 0%2BQzLxNiuh7SAAN06uG3HkzhGiY%3D