require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvertisersController do

  # This should return the minimal set of attributes required to create a valid
  # Advertiser. As you add validations to Advertiser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all advertisers as @advertisers" do
      advertiser = Advertiser.create! valid_attributes
      get :index
      assigns(:advertisers).should eq([advertiser])
    end
  end

  describe "GET show" do
    it "assigns the requested advertiser as @advertiser" do
      advertiser = Advertiser.create! valid_attributes
      get :show, :id => advertiser.id
      assigns(:advertiser).should eq(advertiser)
    end
  end

  describe "GET new" do
    it "assigns a new advertiser as @advertiser" do
      get :new
      assigns(:advertiser).should be_a_new(Advertiser)
    end
  end

  describe "GET edit" do
    it "assigns the requested advertiser as @advertiser" do
      advertiser = Advertiser.create! valid_attributes
      get :edit, :id => advertiser.id
      assigns(:advertiser).should eq(advertiser)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Advertiser" do
        expect {
          post :create, :advertiser => valid_attributes
        }.to change(Advertiser, :count).by(1)
      end

      it "assigns a newly created advertiser as @advertiser" do
        post :create, :advertiser => valid_attributes
        assigns(:advertiser).should be_a(Advertiser)
        assigns(:advertiser).should be_persisted
      end

      it "redirects to the created advertiser" do
        post :create, :advertiser => valid_attributes
        response.should redirect_to(Advertiser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advertiser as @advertiser" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertiser.any_instance.stub(:save).and_return(false)
        post :create, :advertiser => {}
        assigns(:advertiser).should be_a_new(Advertiser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertiser.any_instance.stub(:save).and_return(false)
        post :create, :advertiser => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advertiser" do
        advertiser = Advertiser.create! valid_attributes
        # Assuming there are no other advertisers in the database, this
        # specifies that the Advertiser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Advertiser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => advertiser.id, :advertiser => {'these' => 'params'}
      end

      it "assigns the requested advertiser as @advertiser" do
        advertiser = Advertiser.create! valid_attributes
        put :update, :id => advertiser.id, :advertiser => valid_attributes
        assigns(:advertiser).should eq(advertiser)
      end

      it "redirects to the advertiser" do
        advertiser = Advertiser.create! valid_attributes
        put :update, :id => advertiser.id, :advertiser => valid_attributes
        response.should redirect_to(advertiser)
      end
    end

    describe "with invalid params" do
      it "assigns the advertiser as @advertiser" do
        advertiser = Advertiser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertiser.any_instance.stub(:save).and_return(false)
        put :update, :id => advertiser.id, :advertiser => {}
        assigns(:advertiser).should eq(advertiser)
      end

      it "re-renders the 'edit' template" do
        advertiser = Advertiser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertiser.any_instance.stub(:save).and_return(false)
        put :update, :id => advertiser.id, :advertiser => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advertiser" do
      advertiser = Advertiser.create! valid_attributes
      expect {
        delete :destroy, :id => advertiser.id
      }.to change(Advertiser, :count).by(-1)
    end

    it "redirects to the advertisers list" do
      advertiser = Advertiser.create! valid_attributes
      delete :destroy, :id => advertiser.id
      response.should redirect_to(advertisers_url)
    end
  end

end
