require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AudiencesLocationsController do

  # This should return the minimal set of attributes required to create a valid
  # AudiencesLocation. As you add validations to AudiencesLocation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all audiences_locations as @audiences_locations" do
      audiences_location = AudiencesLocation.create! valid_attributes
      get :index
      assigns(:audiences_locations).should eq([audiences_location])
    end
  end

  describe "GET show" do
    it "assigns the requested audiences_location as @audiences_location" do
      audiences_location = AudiencesLocation.create! valid_attributes
      get :show, :id => audiences_location.id
      assigns(:audiences_location).should eq(audiences_location)
    end
  end

  describe "GET new" do
    it "assigns a new audiences_location as @audiences_location" do
      get :new
      assigns(:audiences_location).should be_a_new(AudiencesLocation)
    end
  end

  describe "GET edit" do
    it "assigns the requested audiences_location as @audiences_location" do
      audiences_location = AudiencesLocation.create! valid_attributes
      get :edit, :id => audiences_location.id
      assigns(:audiences_location).should eq(audiences_location)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AudiencesLocation" do
        expect {
          post :create, :audiences_location => valid_attributes
        }.to change(AudiencesLocation, :count).by(1)
      end

      it "assigns a newly created audiences_location as @audiences_location" do
        post :create, :audiences_location => valid_attributes
        assigns(:audiences_location).should be_a(AudiencesLocation)
        assigns(:audiences_location).should be_persisted
      end

      it "redirects to the created audiences_location" do
        post :create, :audiences_location => valid_attributes
        response.should redirect_to(AudiencesLocation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved audiences_location as @audiences_location" do
        # Trigger the behavior that occurs when invalid params are submitted
        AudiencesLocation.any_instance.stub(:save).and_return(false)
        post :create, :audiences_location => {}
        assigns(:audiences_location).should be_a_new(AudiencesLocation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AudiencesLocation.any_instance.stub(:save).and_return(false)
        post :create, :audiences_location => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested audiences_location" do
        audiences_location = AudiencesLocation.create! valid_attributes
        # Assuming there are no other audiences_locations in the database, this
        # specifies that the AudiencesLocation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AudiencesLocation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => audiences_location.id, :audiences_location => {'these' => 'params'}
      end

      it "assigns the requested audiences_location as @audiences_location" do
        audiences_location = AudiencesLocation.create! valid_attributes
        put :update, :id => audiences_location.id, :audiences_location => valid_attributes
        assigns(:audiences_location).should eq(audiences_location)
      end

      it "redirects to the audiences_location" do
        audiences_location = AudiencesLocation.create! valid_attributes
        put :update, :id => audiences_location.id, :audiences_location => valid_attributes
        response.should redirect_to(audiences_location)
      end
    end

    describe "with invalid params" do
      it "assigns the audiences_location as @audiences_location" do
        audiences_location = AudiencesLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AudiencesLocation.any_instance.stub(:save).and_return(false)
        put :update, :id => audiences_location.id, :audiences_location => {}
        assigns(:audiences_location).should eq(audiences_location)
      end

      it "re-renders the 'edit' template" do
        audiences_location = AudiencesLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AudiencesLocation.any_instance.stub(:save).and_return(false)
        put :update, :id => audiences_location.id, :audiences_location => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested audiences_location" do
      audiences_location = AudiencesLocation.create! valid_attributes
      expect {
        delete :destroy, :id => audiences_location.id
      }.to change(AudiencesLocation, :count).by(-1)
    end

    it "redirects to the audiences_locations list" do
      audiences_location = AudiencesLocation.create! valid_attributes
      delete :destroy, :id => audiences_location.id
      response.should redirect_to(audiences_locations_url)
    end
  end

end
