require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InfluencersController do

  # This should return the minimal set of attributes required to create a valid
  # Influencer. As you add validations to Influencer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all influencers as @influencers" do
      influencer = Influencer.create! valid_attributes
      get :index
      assigns(:influencers).should eq([influencer])
    end
  end

  describe "GET show" do
    it "assigns the requested influencer as @influencer" do
      influencer = Influencer.create! valid_attributes
      get :show, :id => influencer.id
      assigns(:influencer).should eq(influencer)
    end
  end

  describe "GET new" do
    it "assigns a new influencer as @influencer" do
      get :new
      assigns(:influencer).should be_a_new(Influencer)
    end
  end

  describe "GET edit" do
    it "assigns the requested influencer as @influencer" do
      influencer = Influencer.create! valid_attributes
      get :edit, :id => influencer.id
      assigns(:influencer).should eq(influencer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Influencer" do
        expect {
          post :create, :influencer => valid_attributes
        }.to change(Influencer, :count).by(1)
      end

      it "assigns a newly created influencer as @influencer" do
        post :create, :influencer => valid_attributes
        assigns(:influencer).should be_a(Influencer)
        assigns(:influencer).should be_persisted
      end

      it "redirects to the created influencer" do
        post :create, :influencer => valid_attributes
        response.should redirect_to(Influencer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved influencer as @influencer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Influencer.any_instance.stub(:save).and_return(false)
        post :create, :influencer => {}
        assigns(:influencer).should be_a_new(Influencer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Influencer.any_instance.stub(:save).and_return(false)
        post :create, :influencer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested influencer" do
        influencer = Influencer.create! valid_attributes
        # Assuming there are no other influencers in the database, this
        # specifies that the Influencer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Influencer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => influencer.id, :influencer => {'these' => 'params'}
      end

      it "assigns the requested influencer as @influencer" do
        influencer = Influencer.create! valid_attributes
        put :update, :id => influencer.id, :influencer => valid_attributes
        assigns(:influencer).should eq(influencer)
      end

      it "redirects to the influencer" do
        influencer = Influencer.create! valid_attributes
        put :update, :id => influencer.id, :influencer => valid_attributes
        response.should redirect_to(influencer)
      end
    end

    describe "with invalid params" do
      it "assigns the influencer as @influencer" do
        influencer = Influencer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Influencer.any_instance.stub(:save).and_return(false)
        put :update, :id => influencer.id, :influencer => {}
        assigns(:influencer).should eq(influencer)
      end

      it "re-renders the 'edit' template" do
        influencer = Influencer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Influencer.any_instance.stub(:save).and_return(false)
        put :update, :id => influencer.id, :influencer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested influencer" do
      influencer = Influencer.create! valid_attributes
      expect {
        delete :destroy, :id => influencer.id
      }.to change(Influencer, :count).by(-1)
    end

    it "redirects to the influencers list" do
      influencer = Influencer.create! valid_attributes
      delete :destroy, :id => influencer.id
      response.should redirect_to(influencers_url)
    end
  end

end
