require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TopFollowersController do

  # This should return the minimal set of attributes required to create a valid
  # TopFollower. As you add validations to TopFollower, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all top_followers as @top_followers" do
      top_follower = TopFollower.create! valid_attributes
      get :index
      assigns(:top_followers).should eq([top_follower])
    end
  end

  describe "GET show" do
    it "assigns the requested top_follower as @top_follower" do
      top_follower = TopFollower.create! valid_attributes
      get :show, :id => top_follower.id
      assigns(:top_follower).should eq(top_follower)
    end
  end

  describe "GET new" do
    it "assigns a new top_follower as @top_follower" do
      get :new
      assigns(:top_follower).should be_a_new(TopFollower)
    end
  end

  describe "GET edit" do
    it "assigns the requested top_follower as @top_follower" do
      top_follower = TopFollower.create! valid_attributes
      get :edit, :id => top_follower.id
      assigns(:top_follower).should eq(top_follower)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TopFollower" do
        expect {
          post :create, :top_follower => valid_attributes
        }.to change(TopFollower, :count).by(1)
      end

      it "assigns a newly created top_follower as @top_follower" do
        post :create, :top_follower => valid_attributes
        assigns(:top_follower).should be_a(TopFollower)
        assigns(:top_follower).should be_persisted
      end

      it "redirects to the created top_follower" do
        post :create, :top_follower => valid_attributes
        response.should redirect_to(TopFollower.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved top_follower as @top_follower" do
        # Trigger the behavior that occurs when invalid params are submitted
        TopFollower.any_instance.stub(:save).and_return(false)
        post :create, :top_follower => {}
        assigns(:top_follower).should be_a_new(TopFollower)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TopFollower.any_instance.stub(:save).and_return(false)
        post :create, :top_follower => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested top_follower" do
        top_follower = TopFollower.create! valid_attributes
        # Assuming there are no other top_followers in the database, this
        # specifies that the TopFollower created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TopFollower.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => top_follower.id, :top_follower => {'these' => 'params'}
      end

      it "assigns the requested top_follower as @top_follower" do
        top_follower = TopFollower.create! valid_attributes
        put :update, :id => top_follower.id, :top_follower => valid_attributes
        assigns(:top_follower).should eq(top_follower)
      end

      it "redirects to the top_follower" do
        top_follower = TopFollower.create! valid_attributes
        put :update, :id => top_follower.id, :top_follower => valid_attributes
        response.should redirect_to(top_follower)
      end
    end

    describe "with invalid params" do
      it "assigns the top_follower as @top_follower" do
        top_follower = TopFollower.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TopFollower.any_instance.stub(:save).and_return(false)
        put :update, :id => top_follower.id, :top_follower => {}
        assigns(:top_follower).should eq(top_follower)
      end

      it "re-renders the 'edit' template" do
        top_follower = TopFollower.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TopFollower.any_instance.stub(:save).and_return(false)
        put :update, :id => top_follower.id, :top_follower => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested top_follower" do
      top_follower = TopFollower.create! valid_attributes
      expect {
        delete :destroy, :id => top_follower.id
      }.to change(TopFollower, :count).by(-1)
    end

    it "redirects to the top_followers list" do
      top_follower = TopFollower.create! valid_attributes
      delete :destroy, :id => top_follower.id
      response.should redirect_to(top_followers_url)
    end
  end

end
