development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: social_target_dev
  pool: 5
  username: social_target
  password: fdAHIbh38FDwe
  host: socialtarget.calv1pb3okmi.us-east-1.rds.amazonaws.com
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: social_target_test
  username: social_target
  password: fdAHIbh38FDwe
  host: socialtarget.calv1pb3okmi.us-east-1.rds.amazonaws.com

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: social_target_mx
  username: social_target
  password: fdAHIbh38FDwe
  host: socialtarget.calv1pb3okmi.us-east-1.rds.amazonaws.com
